// ============================================================
// DIPLOMATIQ — MUN OFFICIAL CODE OF CONDUCT
// Version 1.0 — Effective September 2026
// 36 Sections with comprehensive rules
// ============================================================

import {
  Shield, Users, Gavel, Building2, GraduationCap, Crown,
  Shirt, BookOpen, Scale, Search, FileText, PenTool,
  Monitor, MessageSquare, MessageCircle, Video,
  Share2, Heart, AlertTriangle, Globe, Lock,
  Fingerprint, Handshake, Flag, ScrollText, AlertCircle,
  Settings, School, Building, Plane, Compass,
  TrendingUp, UsersRound, CheckCircle2
} from 'lucide-react'

export interface ConductRule {
  number: string
  text: string
}

export interface ConductSection {
  id: string
  number: number
  title: string
  icon: React.ElementType
  color: string
  rules: ConductRule[]
}

export const CODE_OF_CONDUCT_VERSION = '1.0'
export const CODE_OF_CONDUCT_EFFECTIVE = 'September 2026'

export const INTRODUCTION = "The MUN Official Code of Conduct establishes the standards of behavior, professionalism, integrity, diplomacy, and respect expected of all participants using the platform and participating in Model United Nations activities, conferences, committees, simulations, training programs, and educational events."

export const SECTIONS: ConductSection[] = [
  // ──────────────────────────────────────────────
  // 1. GENERAL PRINCIPLES
  // ──────────────────────────────────────────────
  {
    id: 'general-principles', number: 1, title: 'General Principles', icon: Shield, color: '#0A7E8C',
    rules: [
      { number: '1.1', text: 'All participants shall uphold the values of the United Nations, including respect for human rights, dignity, international cooperation, and the peaceful resolution of disputes.' },
      { number: '1.2', text: 'Delegates shall represent their assigned country\'s position accurately and professionally, even when it differs from their personal opinions or beliefs.' },
      { number: '1.3', text: 'Participants shall treat fellow delegates, chairs, advisors, teachers, administrators, and platform users with courtesy, professionalism, and respect at all times.' },
      { number: '1.4', text: 'Academic integrity is paramount. Plagiarism, fabrication of sources, misrepresentation of information, and dishonest conduct are strictly prohibited.' },
      { number: '1.5', text: 'All participants shall contribute to creating an inclusive, welcoming environment free from discrimination based on nationality, ethnicity, race, religion, gender, disability, language, or socioeconomic background.' },
      { number: '1.6', text: 'Participants shall conduct themselves in a manner that reflects positively upon their school, institution, conference, and the wider MUN community.' },
      { number: '1.7', text: 'The principles of diplomatic conduct extend to all interactions — both formal committee sessions and informal exchanges, whether in-person or digital.' },
      { number: '1.8', text: 'No participant shall use their position, influence, or authority to coerce, manipulate, or intimidate another participant for any purpose.' },
      { number: '1.9', text: 'Participants shall respect the confidentiality of sensitive information shared during committee sessions, crisis simulations, and private diplomatic negotiations unless disclosure is required for safety or legal compliance.' },
      { number: '1.10', text: 'The spirit of Model United Nations is educational. Participants shall prioritize learning, growth, and collaboration over competitive advantage at the expense of others.' },
      { number: '1.11', text: 'All participants acknowledge that MUN is a simulation designed to develop skills and understanding. Actions taken in simulation do not represent real-world political positions or endorsements.' },
      { number: '1.12', text: 'Participants shall not misrepresent their identity, qualifications, school affiliation, or any other material fact when registering for or participating in any MUN activity.' },
      { number: '1.13', text: 'Constructive disagreement is foundational to diplomacy. Participants are encouraged to challenge ideas vigorously while respecting the individuals who hold them.' },
      { number: '1.14', text: 'All participants have a responsibility to report violations of this Code of Conduct through the appropriate channels without fear of retaliation.' },
      { number: '1.15', text: 'Ignorance of this Code of Conduct does not excuse violations. All participants are expected to read, understand, and abide by its provisions.' },
      { number: '1.16', text: 'This Code of Conduct applies to all DiplomatiQ platform activities, including but not limited to: assessments, training courses, conference management, research submissions, chat communications, and video sessions.' },
      { number: '1.17', text: 'Participants shall not engage in any activity that undermines the educational purpose, integrity, or reputation of the DiplomatiQ platform or the Model United Nations community.' },
      { number: '1.18', text: 'Cultural, religious, and personal differences shall be respected at all times. What may be acceptable in one cultural context may be offensive in another; participants shall exercise cultural sensitivity.' },
      { number: '1.19', text: 'Participants shall comply with all applicable local, national, and international laws, including those relating to data protection, intellectual property, and online conduct.' },
      { number: '1.20', text: 'The DiplomatiQ platform reserves the right to update this Code of Conduct. Participants will be notified of material changes and are bound by the most current version.' },
    ],
  },

  // ──────────────────────────────────────────────
  // 2. DELEGATE CONDUCT
  // ──────────────────────────────────────────────
  {
    id: 'delegate-conduct', number: 2, title: 'Delegate Conduct', icon: Users, color: '#2563EB',
    rules: [
      { number: '2.1', text: 'Delegates shall prepare thoroughly for committee sessions by researching their assigned country, agenda topics, international agreements, and relevant geopolitical developments.' },
      { number: '2.2', text: 'Delegates shall use proper parliamentary language and diplomatic etiquette when addressing chairs and fellow delegates, including formal salutations such as "Honorable Chair" and "Fellow Delegates."' },
      { number: '2.3', text: 'Delegates shall not interrupt speakers except through approved parliamentary motions and points.' },
      { number: '2.4', text: 'All speeches, interventions, and statements shall remain relevant to the agenda and contribute constructively to debate.' },
      { number: '2.5', text: 'Delegates shall actively participate in working groups, negotiations, and drafting processes rather than passively observing.' },
      { number: '2.6', text: 'Delegates shall pursue consensus-building and collaborative problem-solving whenever possible, prioritizing collective progress over individual recognition.' },
      { number: '2.7', text: 'Personal attacks, insults, intimidation, discriminatory remarks, or disrespectful behavior shall result in disciplinary action.' },
      { number: '2.8', text: 'Delegates shall maintain professional conduct during both formal sessions and informal committee interactions, including breaks, social events, and online communications.' },
      { number: '2.9', text: 'Delegates shall not fabricate or misrepresent their country\'s foreign policy positions, voting record, or international commitments.' },
      { number: '2.10', text: 'Delegates shall respect speaking time limits and yield the floor promptly when their time has elapsed.' },
      { number: '2.11', text: 'During unmoderated caucuses, delegates shall engage in substantive negotiation and coalition-building, not socializing to the exclusion of committee work.' },
      { number: '2.12', text: 'Delegates shall not engage in bloc voting or alliance formations based solely on personal friendships, excluding substantive diplomatic considerations.' },
      { number: '2.13', text: 'Delegates representing countries in the Security Council shall understand and respect the veto power of permanent members without abusing procedural knowledge to obstruct debate.' },
      { number: '2.14', text: 'Delegates shall not submit resolutions or working papers that have been substantially copied from real United Nations documents without proper attribution and original operative contributions.' },
      { number: '2.15', text: 'Delegates shall honor commitments made during negotiations. Reneging on agreed positions without justification undermines trust and diplomatic progress.' },
      { number: '2.16', text: 'Delegates shall not deliberately mislead other delegates about their country\'s position or intentions in order to gain tactical advantage.' },
      { number: '2.17', text: 'When receiving awards or recognition, delegates shall display humility and grace, acknowledging the contributions of their fellow delegates.' },
      { number: '2.18', text: 'Delegates shall not use personal electronic devices during formal committee sessions except for approved research purposes.' },
      { number: '2.19', text: 'Delegates shall remain in the committee room during formal sessions unless excused by the Chair. Extended absences demonstrate disrespect for the proceedings.' },
      { number: '2.20', text: 'Delegates shall report any procedural irregularities or ethical concerns to the Chair through appropriate channels rather than addressing them through disruptive means.' },
      { number: '2.21', text: 'Delegates shall not claim to represent or speak on behalf of countries, organizations, or entities they have not been officially assigned.' },
      { number: '2.22', text: 'When writing crisis notes or directives, delegates shall remain in character and act within the realistic authority and resources of their assigned role.' },
      { number: '2.23', text: 'Delegates shall not engage in side conversations or whispering during formal debate that disrupts the proceedings or excludes other participants.' },
      { number: '2.24', text: 'Delegates shall respect the physical space of the committee room, including proper placement of placards, materials, and personal belongings.' },
      { number: '2.25', text: 'Delegates who feel unwell, distressed, or unsafe during any MUN activity shall inform their advisor, the Chair, or a designated safeguarding officer immediately.' },
    ],
  },

  // ──────────────────────────────────────────────
  // 3. CHAIR RESPONSIBILITIES
  // ──────────────────────────────────────────────
  {
    id: 'chair-responsibilities', number: 3, title: 'Chair Responsibilities', icon: Gavel, color: '#D4A843',
    rules: [
      { number: '3.1', text: 'The Chair shall maintain order and ensure that all committee proceedings follow the established rules of procedure consistently and impartially.' },
      { number: '3.2', text: 'The Chair shall manage the General Speakers List equitably, ensuring all delegates have the opportunity to participate regardless of their experience level or country assignment.' },
      { number: '3.3', text: 'The Chair shall make rulings on points and motions promptly, clearly, and in accordance with parliamentary procedure, providing brief explanations when requested.' },
      { number: '3.4', text: 'The Chair shall not show favoritism toward any delegate, country, or bloc. All participants shall receive equal treatment under the rules.' },
      { number: '3.5', text: 'The Chair shall set appropriate speaking times and caucus durations that balance thorough debate with efficient use of committee time.' },
      { number: '3.6', text: 'The Chair shall ensure that all delegates understand the procedural requirements for submitting resolutions, amendments, and working papers.' },
      { number: '3.7', text: 'The Chair shall intervene proactively when debate becomes unproductive, repetitive, or hostile, redirecting the committee toward constructive discussion.' },
      { number: '3.8', text: 'The Chair shall protect the rights of minority voices in the committee, ensuring that less assertive delegates are not silenced by more dominant participants.' },
      { number: '3.9', text: 'The Chair shall not use their position to advance a particular substantive outcome or influence the content of resolutions beyond procedural guidance.' },
      { number: '3.10', text: 'The Chair shall maintain a professional demeanor at all times, including during moments of procedural confusion or delegate conflict.' },
      { number: '3.11', text: 'The Chair shall be thoroughly prepared for each session, having reviewed all submitted working papers, draft resolutions, and relevant background materials.' },
      { number: '3.12', text: 'The Chair shall provide clear and accurate verbal and written instructions for all voting procedures, including roll call votes and division of the question.' },
      { number: '3.13', text: 'The Chair shall document all significant procedural decisions and their rationale for the conference record and potential appeals.' },
      { number: '3.14', text: 'The Chair shall consult with their co-Chair and the Secretariat on matters of significant procedural uncertainty or ethical concern.' },
      { number: '3.15', text: 'The Chair shall not publicly reprimand or embarrass a delegate for procedural errors. Corrections shall be made with courtesy and educational intent.' },
      { number: '3.16', text: 'The Chair shall ensure that crisis updates are delivered clearly and that delegates have sufficient time to process new information before being expected to respond.' },
      { number: '3.17', text: 'The Chair shall manage time effectively to ensure the committee can complete its work, including resolution drafting, amendment consideration, and voting.' },
      { number: '3.18', text: 'The Chair shall not leave the committee unattended during formal session. If a brief absence is necessary, the co-Chair shall assume the gavel.' },
      { number: '3.19', text: 'The Chair shall write a comprehensive committee report summarizing the proceedings, key decisions, and outcomes for the conference record.' },
      { number: '3.20', text: 'The Chair shall be available to delegates who wish to discuss procedural questions or concerns outside of formal session, providing guidance without compromising impartiality.' },
    ],
  },

  // ──────────────────────────────────────────────
  // 4. SECRETARIAT RESPONSIBILITIES
  // ──────────────────────────────────────────────
  {
    id: 'secretariat-responsibilities', number: 4, title: 'Secretariat Responsibilities', icon: Building2, color: '#7C3AED',
    rules: [
      { number: '4.1', text: 'The Secretariat shall plan and organize all aspects of the conference with professionalism, transparency, and attention to delegate welfare.' },
      { number: '4.2', text: 'The Secretary-General shall serve as the ultimate authority on all conference matters, delegating responsibilities appropriately while maintaining oversight.' },
      { number: '4.3', text: 'The Secretariat shall ensure that all chairs are properly trained in parliamentary procedure, conflict resolution, and safeguarding before the conference begins.' },
      { number: '4.4', text: 'The Secretariat shall establish and communicate clear procedures for emergency situations, including medical emergencies, security concerns, and facility evacuations.' },
      { number: '4.5', text: 'The Secretariat shall handle all complaints and disciplinary matters impartially, following established protocols and ensuring due process for all parties.' },
      { number: '4.6', text: 'The Secretariat shall not disclose confidential delegate information, including medical conditions, personal circumstances, or disciplinary records, without proper authorization.' },
      { number: '4.7', text: 'The Secretariat shall ensure that conference venues are safe, accessible, and appropriate for all participants, including those with disabilities.' },
      { number: '4.8', text: 'The Secretariat shall establish clear communication channels for delegates, advisors, and staff to report concerns or request assistance at any time.' },
      { number: '4.9', text: 'The Secretariat shall manage conference finances responsibly, providing transparent accounting of registration fees and expenditures.' },
      { number: '4.10', text: 'The Secretariat shall ensure that country and committee assignments are made fairly, avoiding conflicts of interest and providing adequate preparation time.' },
      { number: '4.11', text: 'The Secretariat shall prepare comprehensive background guides that are accurate, balanced, and provide sufficient context for informed debate.' },
      { number: '4.12', text: 'The Secretariat shall establish and enforce clear deadlines for position paper submissions, resolution drafting, and other conference deliverables.' },
      { number: '4.13', text: 'The Secretariat shall ensure that opening and closing ceremonies are conducted with appropriate dignity, inclusivity, and professionalism.' },
      { number: '4.14', text: 'The Secretariat shall designate safeguarding officers who are trained to handle concerns about student welfare, including mental health crises.' },
      { number: '4.15', text: 'The Secretariat shall not consume alcohol or use substances that impair judgment during the conference, and shall discourage such behavior among all participants.' },
      { number: '4.16', text: 'The Secretariat shall ensure that crisis scenarios are appropriate for the age group and do not contain content that could traumatize or deeply distress participants.' },
      { number: '4.17', text: 'The Secretariat shall create a post-conference evaluation process to gather feedback and continuously improve future events.' },
      { number: '4.18', text: 'The Secretariat shall maintain relationships with participating schools and institutions with professionalism, responding to inquiries promptly and respectfully.' },
      { number: '4.19', text: 'The Secretariat shall establish a clear chain of command for decision-making during the conference, with defined escalation procedures for serious matters.' },
      { number: '4.20', text: 'The Secretariat shall ensure that all conference materials, including digital content, comply with intellectual property laws and give proper attribution to sources.' },
    ],
  },

  // ──────────────────────────────────────────────
  // 5. TEACHER & ADVISOR RESPONSIBILITIES
  // ──────────────────────────────────────────────
  {
    id: 'teacher-advisor-responsibilities', number: 5, title: 'Teacher & Advisor Responsibilities', icon: GraduationCap, color: '#059669',
    rules: [
      { number: '5.1', text: 'Teachers and advisors shall ensure that their students are adequately prepared for MUN participation, including research, procedure, and conduct expectations.' },
      { number: '5.2', text: 'Teachers and advisors shall provide appropriate supervision during conferences and MUN activities, remaining available for student support without interfering in committee proceedings.' },
      { number: '5.3', text: 'Teachers and advisors shall not write or substantially edit student position papers, resolutions, or speeches. Guidance is encouraged; authorship must remain the student\'s.' },
      { number: '5.4', text: 'Teachers and advisors shall model professional and ethical behavior, recognizing that students look to them as examples of diplomatic conduct.' },
      { number: '5.5', text: 'Teachers and advisors shall respect the authority of the Chair and Secretariat, raising concerns through proper channels rather than disrupting proceedings.' },
      { number: '5.6', text: 'Teachers and advisors shall be familiar with this Code of Conduct and ensure their students understand and agree to its provisions before participation.' },
      { number: '5.7', text: 'Teachers and advisors shall report any concerns about student welfare, including signs of distress, bullying, or harassment, to the designated safeguarding officer immediately.' },
      { number: '5.8', text: 'Teachers and advisors shall maintain appropriate professional boundaries with students, avoiding personal relationships that could compromise their supervisory role.' },
      { number: '5.9', text: 'Teachers and advisors shall not use MUN activities to promote personal political views or agenda items that conflict with the educational purpose of the program.' },
      { number: '5.10', text: 'Teachers and advisors shall ensure that all necessary consent forms, medical information, and emergency contacts are submitted before the conference.' },
      { number: '5.11', text: 'Teachers and advisors shall respect the confidentiality of student academic records, assessment results, and personal information shared during MUN activities.' },
      { number: '5.12', text: 'Teachers and advisors shall support student autonomy in committee, allowing delegates to make their own strategic decisions even when the advisor might choose differently.' },
      { number: '5.13', text: 'Teachers and advisors shall not lobby the Chair, Secretariat, or judges for awards on behalf of their students.' },
      { number: '5.14', text: 'Teachers and advisors shall provide constructive feedback to students after the conference, focusing on growth areas and celebrating achievements.' },
      { number: '5.15', text: 'Teachers and advisors shall ensure that their school\'s MUN program operates in compliance with institutional policies, local regulations, and this Code of Conduct.' },
    ],
  },

  // ──────────────────────────────────────────────
  // 6. LEADERSHIP POSITIONS
  // ──────────────────────────────────────────────
  {
    id: 'leadership-positions', number: 6, title: 'Leadership Positions', icon: Crown, color: '#F59E0B',
    rules: [
      { number: '6.1', text: 'The Secretary-General (SG) bears ultimate responsibility for the conference\'s success, delegate welfare, and adherence to this Code of Conduct.' },
      { number: '6.2', text: 'The Deputy Secretary-General (DSG) shall support the SG in all duties and assume full authority in the SG\'s absence.' },
      { number: '6.3', text: 'Under-Secretaries-General (USGs) shall manage their assigned departments — such as delegate affairs, logistics, crisis, or conference services — with diligence and accountability.' },
      { number: '6.4', text: 'Committee Directors shall oversee the substantive quality of committee proceedings, ensuring background guides are accurate and chairs are prepared.' },
      { number: '6.5', text: 'Leaders shall not abuse their authority for personal benefit, including preferential treatment of friends, schoolmates, or delegates from their own institution.' },
      { number: '6.6', text: 'Leaders shall delegate responsibilities effectively, trusting their team members while maintaining appropriate oversight and accountability mechanisms.' },
      { number: '6.7', text: 'Leaders shall make decisions transparently, communicating the rationale for significant decisions to affected parties whenever possible.' },
      { number: '6.8', text: 'Leaders shall prioritize the welfare and safety of all participants above the logistical success or prestige of the conference.' },
      { number: '6.9', text: 'Leaders shall address conflicts within their team promptly and professionally, seeking mediation when necessary rather than allowing tensions to escalate.' },
      { number: '6.10', text: 'Leaders shall plan for succession, mentoring and training the next generation of leaders to ensure program continuity.' },
      { number: '6.11', text: 'Leaders shall not publicly criticize other team members, chairs, or delegates. Constructive feedback shall be delivered privately and respectfully.' },
      { number: '6.12', text: 'Leaders shall recuse themselves from decisions where they have a personal conflict of interest, including matters involving their own school or close associates.' },
      { number: '6.13', text: 'Leaders shall ensure that all communications — whether to delegates, advisors, or staff — are professional, clear, and timely.' },
      { number: '6.14', text: 'Leaders shall maintain confidentiality regarding sensitive information, including disciplinary matters, personal data, and strategic conference decisions.' },
      { number: '6.15', text: 'Leaders shall represent the conference and the DiplomatiQ platform with professionalism at all times, including on social media and in interactions with external stakeholders.' },
    ],
  },

  // ──────────────────────────────────────────────
  // 7. PROFESSIONAL APPEARANCE & DRESS CODE
  // ──────────────────────────────────────────────
  {
    id: 'dress-code', number: 7, title: 'Professional Appearance & Dress Code', icon: Shirt, color: '#EC4899',
    rules: [
      { number: '7.1', text: 'All participants shall wear business formal attire during conference sessions, opening and closing ceremonies, and any official MUN events.' },
      { number: '7.2', text: 'Business formal attire for in-person conferences typically includes suits, dress shirts, blazers, ties, dress pants, skirts, or equivalent professional garments.' },
      { number: '7.3', text: 'Cultural and religious attire is always welcome and respected. No participant shall be required to compromise their cultural or religious dress practices to conform to this dress code.' },
      { number: '7.4', text: 'National dress of the country being represented is appropriate and encouraged, provided it meets the standard of formality expected at a diplomatic event.' },
      { number: '7.5', text: 'Casual attire including jeans, t-shirts, athletic wear, flip-flops, and shorts is not appropriate for formal committee sessions.' },
      { number: '7.6', text: 'For virtual sessions, participants shall maintain the same standard of professional appearance from the waist up, ensuring their visible attire is business formal.' },
      { number: '7.7', text: 'Participants shall ensure their personal grooming meets professional standards consistent with a diplomatic environment.' },
      { number: '7.8', text: 'Accessories and jewelry should be modest and professional. Excessively casual or distracting accessories are not appropriate.' },
      { number: '7.9', text: 'Footwear should be professional and appropriate for the venue. Athletic shoes and casual sandals are not acceptable for formal sessions.' },
      { number: '7.10', text: 'The Chair and Secretariat shall model the dress code standard. If a chair or staff member is inappropriately dressed, the SG or DSG shall address the matter privately.' },
      { number: '7.11', text: 'Delegates who arrive inappropriately dressed may be asked to change before being admitted to the committee room. This shall be handled discreetly and respectfully.' },
      { number: '7.12', text: 'Conference-specific dress requirements, such as themed events or ceremonial attire, shall be communicated well in advance and participation shall be optional.' },
      { number: '7.13', text: 'For outdoor or social events associated with the conference, the dress code may be relaxed at the discretion of the Secretariat, and this shall be communicated clearly.' },
      { number: '7.14', text: 'Delegates shall not wear clothing bearing political slogans, offensive imagery, or messaging that could disrupt the diplomatic atmosphere of the conference.' },
      { number: '7.15', text: 'Personal protective equipment, when required by health regulations, shall not be considered a violation of the dress code and shall be worn as directed.' },
    ],
  },

  // ──────────────────────────────────────────────
  // 8. PARLIAMENTARY PROCEDURE
  // ──────────────────────────────────────────────
  {
    id: 'parliamentary-procedure', number: 8, title: 'Parliamentary Procedure', icon: BookOpen, color: '#0A7E8C',
    rules: [
      { number: '8.1', text: 'All committee sessions shall be conducted according to the parliamentary procedure designated by the conference rules, typically based on Robert\'s Rules of Order as adapted for MUN.' },
      { number: '8.2', text: 'Delegates shall raise their placard to be recognized by the Chair before speaking. Speaking without recognition is out of order.' },
      { number: '8.3', text: 'Motions must be seconded before being considered by the committee, unless the rules specify otherwise.' },
      { number: '8.4', text: 'Delegates shall use the proper terminology for motions, including "motion for a moderated caucus," "motion to set the agenda," and "motion for a roll call vote."' },
      { number: '8.5', text: 'The Chair\'s ruling on procedural matters is final unless appealed according to the established appeals process.' },
      { number: '8.6', text: 'Points of Order take precedence over the current speaker and must be addressed immediately by the Chair.' },
      { number: '8.7', text: 'Delegates shall not use procedural motions as a dilatory tactic to obstruct committee progress. The Chair may rule such motions out of order.' },
      { number: '8.8', text: 'Voting on procedural matters requires a simple majority unless the conference rules specify otherwise.' },
      { number: '8.9', text: 'Voting on substantive matters, including resolutions and amendments, shall follow the procedure designated by the committee type and conference rules.' },
      { number: '8.10', text: 'Delegates shall not reveal their vote during a secret ballot, nor shall they attempt to discover how others voted.' },
      { number: '8.11', text: 'The yield mechanism (yielding to another delegate, to questions, or to the Chair) shall be used properly and not as a means to extend speaking time beyond limits.' },
      { number: '8.12', text: 'Delegates shall not speak on both sides of a substantive vote during the same speakers list cycle.' },
      { number: '8.13', text: 'Division of the question must be requested before voting begins on a resolution, not after votes have been cast.' },
      { number: '8.14', text: 'The right of reply shall be exercised judiciously and only when a delegate feels personally insulted, not merely when they disagree with another delegate\'s argument.' },
      { number: '8.15', text: 'Delegates shall not challenge the Chair\'s authority through disruptive means. Disagreements with rulings shall be addressed through proper appeals processes.' },
    ],
  },

  // ──────────────────────────────────────────────
  // 9-36 (condensed for production — each section with 10-15 substantive rules)
  // ──────────────────────────────────────────────
  {
    id: 'academic-integrity', number: 9, title: 'Academic Integrity', icon: Scale, color: '#DC2626',
    rules: [
      { number: '9.1', text: 'All work submitted through the platform — including position papers, resolutions, research briefs, and assessments — must be the original work of the submitting delegate.' },
      { number: '9.2', text: 'Plagiarism, defined as presenting another person\'s words, ideas, or work as one\'s own without proper attribution, is strictly prohibited and constitutes a serious violation.' },
      { number: '9.3', text: 'Fabrication of sources, statistics, quotations, or any other information is prohibited. All cited information must be verifiable from legitimate sources.' },
      { number: '9.4', text: 'Self-plagiarism — submitting work previously completed for another course or conference without disclosure — is prohibited.' },
      { number: '9.5', text: 'Collaboration on individual assignments is not permitted unless explicitly authorized. Group work must clearly identify each contributor\'s role.' },
      { number: '9.6', text: 'All sources must be properly cited using a recognized citation format (MLA, APA, or Chicago) as specified by the conference or course requirements.' },
      { number: '9.7', text: 'Paraphrasing without attribution constitutes plagiarism. Delegates must acknowledge the source even when rephrasing another\'s ideas.' },
      { number: '9.8', text: 'The use of essay mills, paper-writing services, or paid research assistance is strictly prohibited.' },
      { number: '9.9', text: 'Delegates shall not share their completed work with others for the purpose of enabling plagiarism or academic dishonesty.' },
      { number: '9.10', text: 'Violations of academic integrity will result in a score of zero for the affected work, potential disqualification from the conference, and notification of the delegate\'s school.' },
      { number: '9.11', text: 'Delegates who become aware of academic dishonesty by others have an obligation to report it to the appropriate authority.' },
      { number: '9.12', text: 'Fair use of brief quotations with proper citation is acceptable and encouraged to support arguments with authoritative sources.' },
      { number: '9.13', text: 'Research assistance from teachers, parents, or tutors is permissible for guidance and feedback, but the intellectual work and writing must remain the student\'s own.' },
      { number: '9.14', text: 'Translation of foreign-language sources must be the delegate\'s own work or properly attributed to the translation tool used.' },
      { number: '9.15', text: 'The DiplomatiQ platform employs AI-powered plagiarism and originality detection. Delegates consent to their work being analyzed by these systems upon submission.' },
    ],
  },
  {
    id: 'research-standards', number: 10, title: 'Research Standards', icon: Search, color: '#8B5CF6',
    rules: [
      { number: '10.1', text: 'Delegates shall use reputable, verifiable sources for all research, prioritizing primary sources such as UN documents, treaties, and official government publications.' },
      { number: '10.2', text: 'The CRAAP test (Currency, Relevance, Authority, Accuracy, Purpose) shall be applied to evaluate all sources before inclusion in position papers or resolutions.' },
      { number: '10.3', text: 'Wikipedia and similar crowd-sourced encyclopedias may be used as starting points for orientation but shall not be cited as authoritative sources in formal documents.' },
      { number: '10.4', text: 'Delegates shall cross-reference important claims with at least two independent, credible sources before presenting them as factual in committee.' },
      { number: '10.5', text: 'Statistical data shall be drawn from recognized international organizations (UN agencies, World Bank, WHO, etc.) and properly cited with date of access.' },
      { number: '10.6', text: 'Delegates shall not cherry-pick data to support a predetermined position while ignoring contradictory evidence from equally credible sources.' },
      { number: '10.7', text: 'Images, charts, and infographics used in presentations or documents must be properly attributed to their original source.' },
      { number: '10.8', text: 'Research conducted using the DiplomatiQ Research Lab shall adhere to the same academic integrity standards as any other research method.' },
      { number: '10.9', text: 'Delegates shall maintain organized research notes and be prepared to provide source verification if challenged on factual claims during committee.' },
      { number: '10.10', text: 'The use of classified, leaked, or illegally obtained documents as research sources is prohibited.' },
      { number: '10.11', text: 'Delegates shall distinguish between fact, opinion, and speculation in their research and presentations, clearly indicating the nature of each claim.' },
      { number: '10.12', text: 'Historical sources shall be contextualized appropriately, recognizing that historical perspectives and terminology may differ from contemporary standards.' },
      { number: '10.13', text: 'Delegates shall not cite sources they have not actually read or reviewed. Listing references without genuine engagement constitutes academic dishonesty.' },
      { number: '10.14', text: 'Research involving human subjects (surveys, interviews) requires proper informed consent and ethical review before being used in MUN contexts.' },
      { number: '10.15', text: 'All research produced through the DiplomatiQ platform may be subject to quality review, and delegates shall cooperate with any verification processes.' },
    ],
  },
  {
    id: 'ai-usage-policy', number: 11, title: 'AI Usage Policy', icon: Fingerprint, color: '#06B6D4',
    rules: [
      { number: '11.1', text: 'Artificial intelligence tools may be used as research and writing aids, provided their use is disclosed and the maximum acceptable AI contribution does not exceed 25% of any submitted work.' },
      { number: '11.2', text: 'AI-generated content presented as entirely original work without disclosure constitutes a violation of academic integrity, regardless of the quality of the output.' },
      { number: '11.3', text: 'Acceptable uses of AI include: brainstorming ideas, checking grammar and spelling, generating outlines, finding relevant sources, and exploring alternative perspectives.' },
      { number: '11.4', text: 'Prohibited uses of AI include: generating complete position papers, resolutions, or speeches; fabricating sources or citations; and producing substantive analytical content presented as the delegate\'s own work.' },
      { number: '11.5', text: 'Delegates must indicate which portions of their work were developed with AI assistance by including an "AI Disclosure Statement" with any submission.' },
      { number: '11.6', text: 'The DiplomatiQ Research Lab\'s AI evaluation system will analyze submissions for AI-generated content. Delegates consent to this analysis upon submission.' },
      { number: '11.7', text: 'If AI content exceeds the 25% threshold, the delegate will be notified and given the opportunity to revise and resubmit before any disciplinary action.' },
      { number: '11.8', text: 'AI tools shall not be used to impersonate another person, generate deepfake content, or create misleading materials of any kind.' },
      { number: '11.9', text: 'Delegates shall not use AI to generate fake citations, fabricated statistics, or invented sources that do not exist.' },
      { number: '11.10', text: 'The use of AI during live assessments is prohibited unless explicitly permitted by the assessment instructions.' },
      { number: '11.11', text: 'AI-assisted translation is permitted, but delegates must disclose its use and take responsibility for the accuracy of the translated content.' },
      { number: '11.12', text: 'Delegates shall not input confidential or personal information about other participants into external AI tools.' },
      { number: '11.13', text: 'The AI usage threshold may be adjusted by the platform based on evolving educational standards. Delegates will be notified of changes.' },
      { number: '11.14', text: 'Teachers may set stricter AI usage limits for their students than the platform default. Such limits take precedence for that class\'s submissions.' },
      { number: '11.15', text: 'The DiplomatiQ platform encourages responsible AI literacy as an essential 21st-century skill. The goal is to teach delegates how to use AI ethically, not to prohibit its use entirely.' },
    ],
  },
  {
    id: 'position-papers', number: 12, title: 'Position Papers', icon: FileText, color: '#84CC16',
    rules: [
      { number: '12.1', text: 'Position papers must be the original work of the submitting delegate. Substantial AI-generated content or plagiarism from existing papers is prohibited.' },
      { number: '12.2', text: 'Position papers shall accurately reflect the assigned country\'s foreign policy, not the delegate\'s personal opinions.' },
      { number: '12.3', text: 'All position papers shall follow the standard three-paragraph structure: topic background, country position, and proposed solutions, unless otherwise specified.' },
      { number: '12.4', text: 'Sources cited in position papers must be real, verifiable, and properly attributed. Fabricated citations are a serious academic integrity violation.' },
      { number: '12.5', text: 'Position papers shall be submitted by the deadline specified by the conference or course. Late submissions may not be considered for awards.' },
      { number: '12.6', text: 'Delegates shall not submit position papers that are substantially identical to those submitted by other delegates, even from the same country in different committees.' },
      { number: '12.7', text: 'The recommended length for position papers is 1-2 pages per topic, unless otherwise specified by the conference guidelines.' },
      { number: '12.8', text: 'Position papers shall demonstrate depth of research, including references to specific UN resolutions, treaties, and recent developments.' },
      { number: '12.9', text: 'Delegates shall disclose any AI assistance used in drafting their position paper as required by the AI Usage Policy (Section 11).' },
      { number: '12.10', text: 'Position papers that receive awards may be published on the conference or platform website with the delegate\'s permission. Delegates retain copyright of their original work.' },
    ],
  },
  {
    id: 'resolution-writing', number: 13, title: 'Resolution Writing', icon: PenTool, color: '#F97316',
    rules: [
      { number: '13.1', text: 'Resolutions must be the collaborative original work of the sponsoring delegates. Copying operative clauses from real UN resolutions without original contribution is prohibited.' },
      { number: '13.2', text: 'All resolutions shall follow the proper format: heading, preambular clauses, and operative clauses, as specified by the conference rules of procedure.' },
      { number: '13.3', text: 'Preambular clauses shall use appropriate introductory phrases (Recognizing, Deeply Concerned, Reaffirming, etc.) and provide relevant context for the operative clauses.' },
      { number: '13.4', text: 'Operative clauses shall use appropriate action verbs (Calls Upon, Urges, Decides, Recommends, etc.) and contain specific, actionable, and implementable provisions.' },
      { number: '13.5', text: 'Each operative clause shall address a single specific action. Combining multiple unrelated actions in one clause is improper format.' },
      { number: '13.6', text: 'Amendments to resolutions must be submitted through the proper procedure and shall not be secretly incorporated without the sponsors\' knowledge or a formal vote.' },
      { number: '13.7', text: 'Co-sponsors and signatories shall have genuinely reviewed and agreed to the resolution content. Adding names without consent is prohibited.' },
      { number: '13.8', text: 'Delegates shall not submit "ghost resolutions" — documents written entirely by a single delegate with minimal input from listed sponsors — as this undermines the collaborative nature of MUN.' },
      { number: '13.9', text: 'The use of AI to generate resolution content is subject to the AI Usage Policy (Section 11). AI-generated clauses must be disclosed and may not exceed the 25% threshold.' },
      { number: '13.10', text: 'Resolutions that propose actions beyond the mandate or authority of the committee may be ruled out of order by the Chair.' },
    ],
  },
  {
    id: 'digital-conduct', number: 14, title: 'Digital Conduct', icon: Monitor, color: '#3B82F6',
    rules: [
      { number: '14.1', text: 'All participants shall use the DiplomatiQ platform and associated digital tools responsibly, ethically, and in accordance with this Code of Conduct.' },
      { number: '14.2', text: 'Participants shall not attempt to gain unauthorized access to any part of the platform, other users\' accounts, or restricted areas of any associated systems.' },
      { number: '14.3', text: 'Participants shall not share their login credentials with others. Each user is responsible for all activity that occurs under their account.' },
      { number: '14.4', text: 'The use of bots, automated scripts, or any software to manipulate platform features, including assessments, voting, or leaderboards, is strictly prohibited.' },
      { number: '14.5', text: 'Participants shall respect the privacy of other users and shall not share screenshots, recordings, or content from private conversations without explicit consent.' },
      { number: '14.6', text: 'Any discovered security vulnerabilities shall be reported to the DiplomatiQ team immediately and shall not be exploited or disclosed to others.' },
      { number: '14.7', text: 'Participants shall not upload malware, viruses, or any malicious code to the platform.' },
      { number: '14.8', text: 'The creation of fake accounts, impersonation of other users, or use of the platform under a false identity is prohibited.' },
      { number: '14.9', text: 'Participants shall not use the platform to send spam, chain messages, or unsolicited commercial content.' },
      { number: '14.10', text: 'Digital communications shall maintain the same standard of professionalism and respect as in-person interactions.' },
      { number: '14.11', text: 'Participants shall not use VPNs or other tools to circumvent geographical restrictions, IP bans, or platform security measures.' },
      { number: '14.12', text: 'The use of browser extensions or third-party tools to modify the platform\'s interface or functionality is not supported and may violate the terms of service.' },
      { number: '14.13', text: 'All content uploaded to the platform remains the intellectual property of the creator, but participants grant DiplomatiQ a license to use, store, and process content for platform operations.' },
      { number: '14.14', text: 'Participants shall not use the platform to distribute copyrighted material without proper authorization.' },
      { number: '14.15', text: 'Violation of digital conduct rules may result in immediate account suspension pending investigation.' },
    ],
  },
  {
    id: 'communication-standards', number: 15, title: 'Communication Standards', icon: MessageSquare, color: '#14B8A6',
    rules: [
      { number: '15.1', text: 'All communications on the DiplomatiQ platform shall be professional, constructive, and relevant to the educational purpose of the community.' },
      { number: '15.2', text: 'Formal address conventions shall be used during committee sessions, including "Honorable Chair," "Fellow Delegates," and proper country references.' },
      { number: '15.3', text: 'Delegates shall not use informal language, slang, profanity, or derogatory terms in any platform communication.' },
      { number: '15.4', text: 'Written communications shall demonstrate proper grammar, spelling, and formatting appropriate for a diplomatic and educational context.' },
      { number: '15.5', text: 'Disagreements shall be expressed through substantive argument and evidence, not through personal criticism or dismissive language.' },
      { number: '15.6', text: 'Delegates shall respond to communications in a timely manner, particularly when collaboration on resolutions or working papers is involved.' },
      { number: '15.7', text: 'Confidential communications between delegates during negotiations shall be respected. Unauthorized disclosure of private negotiation positions is a violation of diplomatic trust.' },
      { number: '15.8', text: 'All public communications on the platform are subject to moderation. Content that violates this Code of Conduct may be removed.' },
      { number: '15.9', text: 'Delegates shall not use ALL CAPS for extended text in communications, as this is considered shouting in digital etiquette.' },
      { number: '15.10', text: 'Non-English communications are permitted in designated multilingual spaces, but shall always include a translation or summary for accessibility.' },
    ],
  },
  {
    id: 'chat-room-conduct', number: 16, title: 'Chat Room Conduct', icon: MessageCircle, color: '#6366F1',
    rules: [
      { number: '16.1', text: 'Chat room discussions shall remain on-topic and relevant to the committee, course, or designated subject of the channel.' },
      { number: '16.2', text: 'Participants shall not spam chat rooms with repetitive messages, excessive emojis, or irrelevant content.' },
      { number: '16.3', text: 'Private messaging between delegates is permitted, but harassment, unwanted advances, or persistent unwanted contact through private messages is prohibited.' },
      { number: '16.4', text: 'Delegates shall not share personal contact information (phone numbers, personal email addresses, social media handles) in public chat rooms.' },
      { number: '16.5', text: 'Inappropriate, offensive, or harmful content in chat rooms shall be reported immediately using the in-app reporting feature.' },
      { number: '16.6', text: 'Chat moderators have the authority to remove messages that violate this Code of Conduct and to temporarily mute participants who repeatedly violate chat rules.' },
      { number: '16.7', text: 'Delegates shall not use chat rooms to coordinate violations of this Code of Conduct or to plan disruptive behavior.' },
      { number: '16.8', text: 'Committee-specific chat rooms shall be used for substantive diplomatic communication, not for casual socializing that disrupts other delegates\' work.' },
      { number: '16.9', text: 'File sharing in chat rooms is limited to documents directly relevant to the MUN activity (position papers, draft resolutions, research documents).' },
      { number: '16.10', text: 'Delegates shall not share answers to assessment questions or other academic materials that could enable dishonesty in chat rooms.' },
    ],
  },
  {
    id: 'video-call-conduct', number: 17, title: 'Video Call Conduct', icon: Video, color: '#0EA5E9',
    rules: [
      { number: '17.1', text: 'Participants shall have their cameras on during virtual committee sessions unless experiencing technical difficulties or granted an exemption.' },
      { number: '17.2', text: 'Participants shall ensure their background is appropriate and professional during video calls, using virtual backgrounds if necessary.' },
      { number: '17.3', text: 'Delegates shall maintain the same standard of professional attire for video calls as for in-person sessions.' },
      { number: '17.4', text: 'Microphones shall be muted when not speaking to reduce background noise and ensure clear audio for the active speaker.' },
      { number: '17.5', text: 'Screen sharing shall be used only for presenting relevant materials and shall not display personal or inappropriate content.' },
      { number: '17.6', text: 'Recording of video calls is prohibited without the explicit consent of all participants and the Chair.' },
      { number: '17.7', text: 'Participants shall not use virtual backgrounds or filters that are distracting, inappropriate, or could be considered offensive.' },
      { number: '17.8', text: 'Technical difficulties should be reported to the Chair immediately. Delegates shall not use claimed technical issues to avoid participation.' },
      { number: '17.9', text: 'The chat feature during video calls shall be used for substantive questions and procedural matters, not for side conversations.' },
      { number: '17.10', text: 'Virtual committee sessions follow the same parliamentary procedure and conduct expectations as in-person sessions.' },
    ],
  },
  {
    id: 'social-media-conduct', number: 18, title: 'Social Media Conduct', icon: Share2, color: '#F43F5E',
    rules: [
      { number: '18.1', text: 'Participants shall not post photographs, videos, or audio recordings from conference sessions on social media without the consent of all individuals depicted.' },
      { number: '18.2', text: 'Delegates shall not share confidential committee content, including crisis updates, resolution drafts, or voting results, on social media during or after the conference without authorization.' },
      { number: '18.3', text: 'Social media posts related to DiplomatiQ or MUN activities shall be respectful, professional, and not misrepresent the platform or conference.' },
      { number: '18.4', text: 'Cyberbullying, harassment, or intimidation through social media platforms directed at other MUN participants is a violation of this Code of Conduct and may result in disciplinary action.' },
      { number: '18.5', text: 'Participants shall not create social media accounts, pages, or groups that impersonate the DiplomatiQ platform, conference Secretariat, or any official entity.' },
      { number: '18.6', text: 'Delegates are encouraged to share positive MUN experiences on social media, provided they respect the privacy and consent of others.' },
      { number: '18.7', text: 'Official conference hashtags and social media handles shall be used appropriately and not for spam, self-promotion, or unrelated content.' },
      { number: '18.8', text: 'The DiplomatiQ platform may monitor public social media posts that reference the platform or its events for safeguarding and reputation management purposes.' },
      { number: '18.9', text: 'Negative experiences or complaints about the platform or conference shall be directed to the appropriate support channels rather than aired publicly on social media.' },
      { number: '18.10', text: 'Social media conduct violations may be considered in disciplinary proceedings, even if the violation occurred outside the platform itself.' },
    ],
  },
  {
    id: 'anti-bullying', number: 19, title: 'Anti-Bullying', icon: Heart, color: '#EF4444',
    rules: [
      { number: '19.1', text: 'Bullying of any kind — physical, verbal, relational, or cyber — is strictly prohibited in all DiplomatiQ activities and MUN events.' },
      { number: '19.2', text: 'Physical bullying includes any unwanted physical contact, intimidation through physical presence, or destruction of personal property.' },
      { number: '19.3', text: 'Verbal bullying includes name-calling, mocking, teasing, derogatory language, and persistent unwelcome criticism that targets a person rather than their ideas.' },
      { number: '19.4', text: 'Relational bullying includes social exclusion, spreading rumors, deliberate isolation, and manipulating group dynamics to ostracize an individual.' },
      { number: '19.5', text: 'Cyberbullying includes harassment through digital channels, social media, messaging apps, or the DiplomatiQ platform itself.' },
      { number: '19.6', text: 'Bystanders who witness bullying have a responsibility to intervene or report the behavior. Silence in the face of bullying enables it to continue.' },
      { number: '19.7', text: 'Reports of bullying will be taken seriously and investigated promptly. Complainants will be protected from retaliation.' },
      { number: '19.8', text: 'Bullying behavior, even if framed as "just joking" or "MUN banter," is not acceptable. Impact matters more than intent.' },
      { number: '19.9', text: 'Delegates who experience bullying shall document the incidents (screenshots, timestamps, witnesses) and report them through the established channels.' },
      { number: '19.10', text: 'Consequences for bullying may include mandatory mediation, temporary suspension, or permanent removal from the platform or conference, depending on severity.' },
      { number: '19.11', text: 'Schools and institutions are expected to have their own anti-bullying policies that complement this Code of Conduct.' },
      { number: '19.12', text: 'The DiplomatiQ platform shall provide educational resources about recognizing and preventing bullying in the MUN context.' },
      { number: '19.13', text: 'Power imbalances — such as those between experienced and novice delegates, or between chairs and delegates — shall not be exploited for bullying purposes.' },
      { number: '19.14', text: 'Repeated microaggressions that create a hostile environment are considered a form of bullying under this Code of Conduct.' },
      { number: '19.15', text: 'All participants are entitled to participate in MUN activities without fear of being bullied, regardless of their experience level, background, or ability.' },
    ],
  },
  {
    id: 'anti-harassment', number: 20, title: 'Anti-Harassment', icon: AlertTriangle, color: '#DC2626',
    rules: [
      { number: '20.1', text: 'Harassment of any kind — including sexual, racial, religious, gender-based, or power-based harassment — is strictly prohibited.' },
      { number: '20.2', text: 'Sexual harassment includes unwelcome sexual advances, requests for sexual favors, and other verbal or physical conduct of a sexual nature.' },
      { number: '20.3', text: 'Racial harassment includes racial slurs, stereotypes, derogatory comments about ethnicity, and any behavior that creates a hostile environment based on race.' },
      { number: '20.4', text: 'No participant shall be subjected to harassment based on their gender identity, sexual orientation, disability, or any other protected characteristic.' },
      { number: '20.5', text: 'Harassment can occur in person, through digital communications, or through social media. All forms are equally serious.' },
      { number: '20.6', text: 'Participants who experience harassment shall report it immediately to a designated safeguarding officer, teacher, or through the platform\'s reporting system.' },
      { number: '20.7', text: 'All reports of harassment will be investigated confidentially and with sensitivity to the complainant\'s wellbeing.' },
      { number: '20.8', text: 'Retaliation against anyone who reports harassment in good faith is strictly prohibited and will result in severe disciplinary action.' },
      { number: '20.9', text: 'False accusations of harassment made maliciously are also prohibited, though good-faith reports that cannot be substantiated will not be penalized.' },
      { number: '20.10', text: 'During the investigation of a harassment complaint, appropriate measures shall be taken to separate the parties involved and ensure the complainant\'s safety.' },
      { number: '20.11', text: 'Conference organizers shall designate specific individuals as points of contact for harassment reports, and their contact information shall be widely publicized.' },
      { number: '20.12', text: 'Harassment training shall be included in the orientation for all chairs, staff, and secretariat members.' },
      { number: '20.13', text: 'The DiplomatiQ platform maintains a zero-tolerance policy toward harassment. Even a single verified incident may result in removal from the platform.' },
      { number: '20.14', text: 'Consent is paramount. Behavior that may be welcome by one person may be harassment to another. When in doubt, err on the side of caution and respect.' },
      { number: '20.15', text: 'All participants are encouraged to intervene or seek help if they witness harassment, even if the target does not report it themselves.' },
    ],
  },
  {
    id: 'inclusivity-diversity', number: 21, title: 'Inclusivity & Diversity', icon: Globe, color: '#8B5CF6',
    rules: [
      { number: '21.1', text: 'The DiplomatiQ platform and all MUN activities shall be inclusive and welcoming to participants of all backgrounds, identities, and abilities.' },
      { number: '21.2', text: 'Discrimination based on nationality, ethnicity, race, religion, gender, gender identity, sexual orientation, disability, language, or socioeconomic background is prohibited.' },
      { number: '21.3', text: 'Conference venues and digital platforms shall be accessible to participants with disabilities, including physical, visual, auditory, and cognitive accessibility requirements.' },
      { number: '21.4', text: 'Participants shall use inclusive language that respects diverse gender identities and avoids assumptions about others\' backgrounds or beliefs.' },
      { number: '21.5', text: 'Cultural and religious practices, including prayer times, dietary requirements, and dress customs, shall be respected and accommodated.' },
      { number: '21.6', text: 'Delegates whose first language is not English shall be supported through appropriate accommodations, including extended speaking preparation time where feasible.' },
      { number: '21.7', text: 'Country assignments and committee roles shall be distributed equitably, avoiding patterns that consistently disadvantage any group.' },
      { number: '21.8', text: 'The platform shall actively work to reduce barriers to participation for underrepresented groups, including financial, geographical, and cultural barriers.' },
      { number: '21.9', text: 'Stereotyping of countries, cultures, or peoples during committee sessions — even in the context of role-playing — shall be avoided.' },
      { number: '21.10', text: 'Participants shall not make assumptions about another delegate\'s personal beliefs based on the country they are representing in the simulation.' },
      { number: '21.11', text: 'Pronouns and preferred names shall be respected at all times. Intentional misgendering or deadnaming is a form of harassment.' },
      { number: '21.12', text: 'Conference materials and platform content shall be reviewed for cultural sensitivity and inclusive representation.' },
      { number: '21.13', text: 'Diversity in leadership positions — including chairs, secretariat, and staff — is encouraged and should reflect the diversity of the participant community.' },
      { number: '21.14', text: 'Feedback on inclusivity issues shall be welcomed and addressed promptly. Participants shall not be dismissed for raising concerns about representation or access.' },
      { number: '21.15', text: 'The DiplomatiQ platform commits to continuous improvement in its diversity and inclusion practices, guided by feedback from the community.' },
    ],
  },
  {
    id: 'safeguarding', number: 22, title: 'Safeguarding & Student Welfare', icon: Shield, color: '#059669',
    rules: [
      { number: '22.1', text: 'The safety and welfare of all participants, particularly minors, is the highest priority of the DiplomatiQ platform and all associated MUN activities.' },
      { number: '22.2', text: 'All staff, chairs, and adults in positions of authority shall undergo safeguarding training and background checks as required by applicable law and institutional policy.' },
      { number: '22.3', text: 'No adult shall be alone with a minor in a closed room or private digital space. All interactions shall be observable or interruptible.' },
      { number: '22.4', text: 'Mandatory reporting obligations shall be followed without exception. Any suspicion of child abuse, neglect, or exploitation must be reported to the appropriate authorities.' },
      { number: '22.5', text: 'Delegates exhibiting signs of distress, mental health challenges, or emotional crisis shall be offered support and connected with appropriate resources.' },
      { number: '22.6', text: 'The platform shall maintain a clear safeguarding policy that is accessible to all participants, parents, and guardians.' },
      { number: '22.7', text: 'Parental consent shall be obtained for all minors before participation in any DiplomatiQ activity, including consent for data processing and emergency medical treatment.' },
      { number: '22.8', text: 'Photography and video recording of minors requires explicit parental consent and shall be used only for legitimate educational or promotional purposes.' },
      { number: '22.9', text: 'Emergency procedures, including medical emergencies, mental health crises, and security incidents, shall be established and communicated before every conference.' },
      { number: '22.10', text: 'Designated safeguarding officers shall be present at all in-person events and available during virtual sessions.' },
      { number: '22.11', text: 'Participants shall not be required to disclose personal medical information beyond what is necessary for emergency preparedness.' },
      { number: '22.12', text: 'Reasonable adjustments shall be made for participants with medical conditions, disabilities, or special educational needs.' },
      { number: '22.13', text: 'The platform shall not expose minors to content that is age-inappropriate, including graphic descriptions of violence, sexual content, or extreme psychological stress in crisis scenarios.' },
      { number: '22.14', text: 'Online safety measures shall include content filtering, moderation, and age-appropriate access controls.' },
      { number: '22.15', text: 'All safeguarding concerns shall be documented, investigated, and resolved following established protocols, with records retained as required by law.' },
    ],
  },
  {
    id: 'privacy-data', number: 23, title: 'Privacy & Data Protection', icon: Lock, color: '#64748B',
    rules: [
      { number: '23.1', text: 'The DiplomatiQ platform shall comply with all applicable data protection laws, including the General Data Protection Regulation (GDPR), the Children\'s Online Privacy Protection Act (COPPA), and local data protection regulations.' },
      { number: '23.2', text: 'Personal data shall be collected only for specified, explicit, and legitimate purposes and shall not be processed in a manner incompatible with those purposes.' },
      { number: '23.3', text: 'Participants (or their guardians for minors) shall provide informed consent before their data is collected and processed.' },
      { number: '23.4', text: 'Participants have the right to access, correct, and delete their personal data held by the platform, subject to applicable legal requirements.' },
      { number: '23.5', text: 'Personal data shall not be sold to third parties under any circumstances.' },
      { number: '23.6', text: 'Data sharing with third parties shall be limited to essential service providers who comply with equivalent data protection standards.' },
      { number: '23.7', text: 'The platform shall implement appropriate technical and organizational measures to protect personal data against unauthorized access, loss, or destruction.' },
      { number: '23.8', text: 'Data breaches shall be reported to affected users and relevant authorities within the timeframe required by applicable law.' },
      { number: '23.9', text: 'Analytics and assessment data may be used in aggregated, anonymized form to improve the platform and for research purposes.' },
      { number: '23.10', text: 'Participants may request a complete export of their personal data at any time through the platform settings.' },
    ],
  },
  {
    id: 'cybersecurity', number: 24, title: 'Cybersecurity Awareness', icon: Fingerprint, color: '#0F766E',
    rules: [
      { number: '24.1', text: 'Participants shall use strong, unique passwords for their DiplomatiQ accounts and shall not share them with others.' },
      { number: '24.2', text: 'Two-factor authentication (2FA) is recommended for all accounts and required for accounts with administrative privileges.' },
      { number: '24.3', text: 'Participants shall be vigilant against phishing attempts and shall not click on suspicious links or provide credentials in response to unsolicited communications.' },
      { number: '24.4', text: 'Security incidents, including suspected unauthorized access, shall be reported to the DiplomatiQ security team immediately.' },
      { number: '24.5', text: 'Participants shall keep their devices and browsers updated with the latest security patches.' },
      { number: '24.6', text: 'The use of public Wi-Fi networks for accessing the platform is discouraged. When necessary, participants should use a VPN.' },
      { number: '24.7', text: 'Participants shall not store sensitive information (passwords, personal data) in unencrypted form on shared or public devices.' },
      { number: '24.8', text: 'The DiplomatiQ platform uses encryption for data in transit and at rest. Participants shall not attempt to circumvent these security measures.' },
      { number: '24.9', text: 'Educational content on cybersecurity best practices shall be made available to all participants through the platform.' },
      { number: '24.10', text: 'Regular security audits and penetration testing shall be conducted to identify and address vulnerabilities in the platform.' },
    ],
  },
  {
    id: 'conflict-resolution', number: 25, title: 'Conflict Resolution', icon: Handshake, color: '#CA8A04',
    rules: [
      { number: '25.1', text: 'Conflicts between participants shall be addressed through dialogue and mediation before escalation to formal complaint procedures.' },
      { number: '25.2', text: 'The Chair shall serve as the first point of mediation for conflicts arising during committee sessions.' },
      { number: '25.3', text: 'De-escalation techniques shall be used as the first response to any conflict situation, including active listening, acknowledging concerns, and reframing issues.' },
      { number: '25.4', text: 'When informal resolution is not possible, a neutral third party — such as a member of the Secretariat or a designated mediator — shall be appointed.' },
      { number: '25.5', text: 'All parties to a conflict shall be given equal opportunity to present their perspective before any resolution is determined.' },
      { number: '25.6', text: 'Resolution outcomes shall be documented and communicated to all affected parties.' },
      { number: '25.7', text: 'The goal of conflict resolution is to restore productive working relationships, not to assign blame or punishment.' },
      { number: '25.8', text: 'Cultural differences in communication styles shall be considered during conflict resolution to avoid misinterpretation.' },
      { number: '25.9', text: 'If a conflict involves a potential violation of this Code of Conduct, it shall be referred to the formal complaint procedure (Section 26).' },
      { number: '25.10', text: 'The DiplomatiQ platform may offer virtual mediation services for conflicts arising in online MUN activities.' },
    ],
  },
  {
    id: 'complaint-procedures', number: 26, title: 'Complaint Procedures', icon: Flag, color: '#E11D48',
    rules: [
      { number: '26.1', text: 'Any participant may file a complaint regarding a violation of this Code of Conduct through the in-app reporting feature or by emailing conduct@diplomatiq.io.' },
      { number: '26.2', text: 'Complaints shall include: the nature of the violation, the section(s) of the Code violated, the date and time, any witnesses, and supporting evidence.' },
      { number: '26.3', text: 'Anonymous complaints may be submitted but may be more difficult to investigate thoroughly. Good-faith anonymous reports will still be reviewed.' },
      { number: '26.4', text: 'The DiplomatiQ team shall acknowledge receipt of complaints within 48 hours and provide an estimated timeline for investigation.' },
      { number: '26.5', text: 'Investigations shall be conducted impartially, with both the complainant and respondent given the opportunity to present their account.' },
      { number: '26.6', text: 'All parties involved in a complaint shall maintain confidentiality about the proceedings and shall not discuss the matter with uninvolved parties.' },
      { number: '26.7', text: 'The complainant shall be informed of the outcome of the investigation, including any disciplinary actions taken, to the extent permitted by privacy regulations.' },
      { number: '26.8', text: 'Complaints determined to be frivolous or made in bad faith may result in consequences for the complainant.' },
      { number: '26.9', text: 'In emergency situations involving immediate safety concerns, participants shall contact local emergency services first and then file a complaint.' },
      { number: '26.10', text: 'The DiplomatiQ platform shall maintain records of all complaints and their resolutions for a period consistent with legal requirements and institutional policy.' },
    ],
  },
  {
    id: 'appeals-process', number: 27, title: 'Appeals Process', icon: ScrollText, color: '#7C3AED',
    rules: [
      { number: '27.1', text: 'Any participant who receives a disciplinary decision has the right to appeal within 14 days of being notified of the decision.' },
      { number: '27.2', text: 'Appeals must be submitted in writing to appeals@diplomatiq.io, stating the grounds for appeal and any new evidence.' },
      { number: '27.3', text: 'Valid grounds for appeal include: procedural irregularities, new evidence not available at the time of the original decision, and disproportionate sanctions.' },
      { number: '27.4', text: 'The appeal shall be reviewed by a panel that was not involved in the original decision.' },
      { number: '27.5', text: 'The appeals panel shall render a decision within 14 days of receiving the appeal.' },
      { number: '27.6', text: 'The appeals panel may uphold, modify, or overturn the original decision.' },
      { number: '27.7', text: 'The decision of the appeals panel is final and binding. No further appeals within the DiplomatiQ system are available.' },
      { number: '27.8', text: 'Pending the outcome of an appeal, the original disciplinary decision may be stayed at the discretion of the appeals panel.' },
      { number: '27.9', text: 'Participants shall not face retaliation for filing a good-faith appeal.' },
      { number: '27.10', text: 'In cases involving legal obligations or institutional policies, the appeals process does not override applicable laws or external regulatory requirements.' },
    ],
  },
  {
    id: 'disciplinary-framework', number: 28, title: 'Disciplinary Framework', icon: AlertCircle, color: '#B91C1C',
    rules: [
      { number: '28.1', text: 'Disciplinary actions shall be proportional to the severity of the violation and consider the participant\'s prior conduct and any mitigating circumstances.' },
      { number: '28.2', text: 'Level 1 — Verbal Warning: For minor first-time infractions. Delivered privately by the Chair or staff member. No formal record.' },
      { number: '28.3', text: 'Level 2 — Written Warning: For repeated minor infractions or moderate first-time violations. Documented and placed in the participant\'s file.' },
      { number: '28.4', text: 'Level 3 — Temporary Suspension: For serious violations. The participant is removed from the current activity or session. May last from one session to the remainder of the conference.' },
      { number: '28.5', text: 'Level 4 — Extended Suspension: For very serious violations or repeated serious offenses. The participant is barred from platform activities for a specified period (e.g., 30-90 days).' },
      { number: '28.6', text: 'Level 5 — Permanent Ban: For the most severe violations, including harassment, abuse, fraud, or criminal behavior. The participant is permanently removed from the platform.' },
      { number: '28.7', text: 'In cases involving potential criminal conduct, the matter shall be referred to law enforcement in addition to internal disciplinary action.' },
      { number: '28.8', text: 'The participant\'s school or institution may be notified of disciplinary actions at Level 3 and above.' },
      { number: '28.9', text: 'All disciplinary decisions shall be documented with the nature of the violation, the evidence considered, and the rationale for the sanction.' },
      { number: '28.10', text: 'Progressive discipline is the default approach, but serious violations may warrant immediate escalation to higher levels without prior warnings.' },
      { number: '28.11', text: 'Participants shall not be disciplined for reporting violations in good faith, even if the report cannot be substantiated.' },
      { number: '28.12', text: 'Restorative justice approaches, such as mediation and facilitated dialogue, may be used alongside or instead of punitive measures when appropriate.' },
      { number: '28.13', text: 'The disciplinary framework applies equally to all participants regardless of their role, position, or institutional affiliation.' },
      { number: '28.14', text: 'Records of disciplinary actions shall be retained according to the platform\'s data retention policy and applicable legal requirements.' },
      { number: '28.15', text: 'A participant who has received a disciplinary action may request a review of their record after a period of demonstrated good conduct.' },
    ],
  },
  {
    id: 'platform-rules', number: 29, title: 'Platform Usage Rules', icon: Settings, color: '#64748B',
    rules: [
      { number: '29.1', text: 'Each user shall maintain only one active account on the DiplomatiQ platform. Creating multiple accounts is prohibited.' },
      { number: '29.2', text: 'Users shall not share their account credentials, access tokens, or session cookies with any other person.' },
      { number: '29.3', text: 'The platform shall be used exclusively for its intended educational and MUN-related purposes. Commercial use without authorization is prohibited.' },
      { number: '29.4', text: 'Users shall not upload content that is illegal, obscene, defamatory, threatening, or otherwise objectionable.' },
      { number: '29.5', text: 'The DiplomatiQ API and data endpoints shall not be accessed through unauthorized means or used to scrape or extract data at scale.' },
      { number: '29.6', text: 'Users shall not attempt to reverse engineer, decompile, or modify the platform\'s software or source code.' },
      { number: '29.7', text: 'Feature requests and bug reports shall be submitted through the designated channels, not by exploiting or publicizing vulnerabilities.' },
      { number: '29.8', text: 'The platform reserves the right to suspend or terminate accounts that violate these usage rules without prior warning for serious infractions.' },
      { number: '29.9', text: 'Users shall comply with all applicable export control, sanctions, and trade compliance laws when using the platform.' },
      { number: '29.10', text: 'The DiplomatiQ platform is provided "as is" with no guarantees of uninterrupted availability. Scheduled maintenance will be communicated in advance.' },
    ],
  },
  {
    id: 'school-standards', number: 30, title: 'School Participation Standards', icon: School, color: '#0891B2',
    rules: [
      { number: '30.1', text: 'Schools must register with the DiplomatiQ platform and provide accurate institutional information before their students can participate.' },
      { number: '30.2', text: 'School registration is subject to verification. The platform reserves the right to deny registration to institutions that cannot be verified.' },
      { number: '30.3', text: 'Each participating school shall designate at least one faculty advisor who is responsible for student conduct and welfare during MUN activities.' },
      { number: '30.4', text: 'Schools shall ensure adequate supervision ratios for in-person conferences, as specified by the conference organizer and local regulations.' },
      { number: '30.5', text: 'Schools are responsible for ensuring that their students have read and agreed to this Code of Conduct before participation.' },
      { number: '30.6', text: 'Schools shall provide necessary consent forms, medical information, and emergency contacts in a timely manner.' },
      { number: '30.7', text: 'A school\'s failure to address repeated violations by its students may result in institutional sanctions, including suspension from the platform.' },
      { number: '30.8', text: 'Schools shall not misrepresent their MUN program size, student qualifications, or institutional credentials.' },
      { number: '30.9', text: 'Schools are encouraged to integrate MUN activities into their curriculum in a manner that supports broader educational objectives.' },
      { number: '30.10', text: 'The DiplomatiQ platform may offer school-level analytics and reporting features, which shall be used in accordance with data protection regulations.' },
    ],
  },
  {
    id: 'conference-standards', number: 31, title: 'Conference Participation Standards', icon: Building, color: '#4F46E5',
    rules: [
      { number: '31.1', text: 'All conference participants shall register through the official channels and provide accurate information during the registration process.' },
      { number: '31.2', text: 'Country and committee assignments shall be accepted as designated. Requests for changes shall be submitted through proper channels.' },
      { number: '31.3', text: 'Delegates shall attend all scheduled committee sessions unless excused by the Chair for legitimate reasons.' },
      { number: '31.4', text: 'Position papers shall be submitted by the specified deadline. Late submissions may affect award eligibility.' },
      { number: '31.5', text: 'Participants shall not register for conferences they do not intend to attend, as this deprives other delegates of participation opportunities.' },
      { number: '31.6', text: 'Conference cancellation or withdrawal policies shall be clearly communicated, and participants shall adhere to them.' },
      { number: '31.7', text: 'Awards shall be accepted graciously. Public disputes about award decisions undermine the conference experience for all participants.' },
      { number: '31.8', text: 'Conference-specific rules, including supplementary procedures and guidelines, shall be read and followed in addition to this Code of Conduct.' },
      { number: '31.9', text: 'Delegates shall not leave the conference venue without informing their advisor or the designated supervisory authority.' },
      { number: '31.10', text: 'Post-conference feedback shall be provided honestly and constructively to help improve future events.' },
    ],
  },
  {
    id: 'international-standards', number: 32, title: 'International Event Standards', icon: Plane, color: '#0D9488',
    rules: [
      { number: '32.1', text: 'Participants traveling to international conferences shall ensure they have valid travel documents, including passports and necessary visas, well in advance.' },
      { number: '32.2', text: 'Participants shall familiarize themselves with the laws, customs, and cultural norms of the host country before travel.' },
      { number: '32.3', text: 'Emergency contact information shall be provided to both the conference organizer and the participant\'s home institution before travel.' },
      { number: '32.4', text: 'Travel and health insurance is strongly recommended for all participants attending international events.' },
      { number: '32.5', text: 'Participants shall comply with all health and safety regulations, including vaccination requirements and quarantine protocols as applicable.' },
      { number: '32.6', text: 'Cultural sensitivity training shall be provided for participants attending conferences in regions with significantly different cultural norms.' },
      { number: '32.7', text: 'The conference organizer shall provide emergency procedures and local emergency contact numbers to all participants before the event.' },
      { number: '32.8', text: 'Participants shall not engage in any illegal activity while attending international conferences, including activities that may be legal in their home country but illegal in the host jurisdiction.' },
      { number: '32.9', text: 'Dietary, religious, and accessibility requirements shall be communicated to the organizer in advance so appropriate accommodations can be made.' },
      { number: '32.10', text: 'The DiplomatiQ platform shall provide resources and guidance for schools and delegates participating in international MUN events.' },
    ],
  },
  {
    id: 'ethical-leadership', number: 33, title: 'Ethical Leadership', icon: Compass, color: '#9333EA',
    rules: [
      { number: '33.1', text: 'Leaders at all levels — from delegates to the Secretary-General — shall model ethical behavior and hold themselves to the highest standards of this Code of Conduct.' },
      { number: '33.2', text: 'Leaders shall make decisions transparently and be accountable for the outcomes of those decisions.' },
      { number: '33.3', text: 'Conflicts of interest shall be disclosed promptly. Leaders shall recuse themselves from decisions where they have a personal stake.' },
      { number: '33.4', text: 'Servant leadership — prioritizing the needs and development of others — is the expected leadership model within the DiplomatiQ community.' },
      { number: '33.5', text: 'Leaders shall not use their position to gain personal advantages, including preferential access, social benefits, or career opportunities at the expense of others.' },
      { number: '33.6', text: 'Constructive feedback to team members and subordinates shall be delivered privately and respectfully. Public criticism of team members is unprofessional.' },
      { number: '33.7', text: 'Leaders shall create an environment where all team members feel safe to express concerns, disagree, and propose alternative approaches.' },
      { number: '33.8', text: 'Recognizing the contributions of others is essential. Leaders shall share credit generously and accept responsibility when things go wrong.' },
      { number: '33.9', text: 'Leaders shall invest in the development of their successors, ensuring that institutional knowledge and leadership skills are transferred.' },
      { number: '33.10', text: 'The ethical standards expected of leaders apply at all times — during official activities, social events, and personal conduct that reflects on the DiplomatiQ community.' },
    ],
  },
  {
    id: 'professional-development', number: 34, title: 'Professional Development Expectations', icon: TrendingUp, color: '#16A34A',
    rules: [
      { number: '34.1', text: 'All participants are expected to engage in continuous learning and professional development throughout their MUN journey.' },
      { number: '34.2', text: 'The DiplomatiQ Academy provides structured learning pathways that participants are encouraged to follow systematically.' },
      { number: '34.3', text: 'Assessment results and feedback shall be used constructively to identify areas for improvement and guide development plans.' },
      { number: '34.4', text: 'Participants shall accept feedback with professionalism and a growth mindset, even when the feedback is critical.' },
      { number: '34.5', text: 'Experienced delegates and leaders are encouraged to mentor newer participants, sharing knowledge and supporting their development.' },
      { number: '34.6', text: 'Skill development in areas beyond traditional MUN — including technology, cross-cultural communication, and emotional intelligence — is encouraged.' },
      { number: '34.7', text: 'Participants shall not view assessments as purely evaluative but as diagnostic tools for identifying strengths and growth areas.' },
      { number: '34.8', text: 'Attending workshops, webinars, and training sessions offered by the platform or conference organizers is strongly encouraged.' },
      { number: '34.9', text: 'The pursuit of higher assessment tiers should be motivated by genuine skill development, not merely by the desire for titles or recognition.' },
      { number: '34.10', text: 'Professional development is a lifelong journey. The skills and values cultivated through MUN participation extend far beyond the conference room.' },
    ],
  },
  {
    id: 'community-standards', number: 35, title: 'Community Standards', icon: UsersRound, color: '#2563EB',
    rules: [
      { number: '35.1', text: 'The DiplomatiQ community is built on mutual respect, collaboration, and a shared commitment to diplomatic education.' },
      { number: '35.2', text: 'Participants shall contribute positively to the community through constructive engagement, knowledge sharing, and support for fellow members.' },
      { number: '35.3', text: 'The community shall not tolerate gatekeeping — preventing others from participating based on experience level, background, or perceived ability.' },
      { number: '35.4', text: 'Delegates representing DiplomatiQ or their school at external events shall conduct themselves as ambassadors of the community\'s values.' },
      { number: '35.5', text: 'Community members shall report violations of this Code of Conduct to help maintain a safe and respectful environment for all.' },
      { number: '35.6', text: 'Constructive criticism of the platform, conference, or community practices is welcome and should be directed through appropriate feedback channels.' },
      { number: '35.7', text: 'The community shall celebrate achievements and milestones collectively, recognizing that individual success contributes to collective advancement.' },
      { number: '35.8', text: 'Participants shall not organize or participate in unauthorized activities under the DiplomatiQ name or brand.' },
      { number: '35.9', text: 'Community standards evolve with the community. Participants are encouraged to contribute to the ongoing development of these standards through feedback and dialogue.' },
      { number: '35.10', text: 'The ultimate measure of the DiplomatiQ community\'s success is the positive impact its members have on the world — as diplomats, leaders, and global citizens.' },
    ],
  },
  {
    id: 'acknowledgment', number: 36, title: 'Acknowledgment & Acceptance', icon: CheckCircle2, color: '#059669',
    rules: [
      { number: '36.1', text: 'All participants shall read this Code of Conduct in its entirety before using the DiplomatiQ platform or participating in any MUN activity.' },
      { number: '36.2', text: 'By creating an account on the DiplomatiQ platform, participants confirm that they have read, understood, and agree to abide by this Code of Conduct.' },
      { number: '36.3', text: 'Participants understand that violations of this Code of Conduct may result in disciplinary action, including suspension or removal from the platform, conferences, committees, and leadership positions.' },
      { number: '36.4', text: 'Participants understand that the platform reserves the right to investigate alleged violations and take appropriate action, including referral to law enforcement when necessary.' },
      { number: '36.5', text: 'For participants under the age of 18, a parent or guardian must also acknowledge and accept this Code of Conduct before the minor may use the platform.' },
      { number: '36.6', text: 'Schools and institutions registering on behalf of their students confirm that they have reviewed this Code of Conduct and will ensure student compliance.' },
      { number: '36.7', text: 'This Code of Conduct is a living document that may be updated periodically. Material changes will be communicated to all participants, and continued use of the platform constitutes acceptance of the updated terms.' },
      { number: '36.8', text: 'Questions about this Code of Conduct should be directed to conduct@diplomatiq.io.' },
      { number: '36.9', text: 'Participants who do not agree with this Code of Conduct shall not use the DiplomatiQ platform or participate in any associated activities.' },
      { number: '36.10', text: 'This Code of Conduct was adopted effective September 2026, Version 1.0, and is maintained by the DiplomatiQ platform governance team.' },
    ],
  },
]

// Calculate total rules
export const TOTAL_RULES = SECTIONS.reduce((sum, s) => sum + s.rules.length, 0)
export const TOTAL_SECTIONS = SECTIONS.length
